### ISSUE TITLE
Assist with validating iRule for v11.5.3HF2

### ISSUE THREAD

**Issue by slodewyk** [f5devcentral/f5-tetration#1]
Please assist with validating iRule to run on v11.5.3 as the customer estate that it is required for is currently on v11.5.3HF2

Upgrading to any version of v12 will take at least a few months to be considered.

**Comment by scshitole** [comment]
@slodewyk I validated the iRule with v11.5.3, v11.5.3 does not support the IPFIX element type in this release .   
![image](https://user-images.githubusercontent.com/13858248/43545935-1fa3f4dc-958c-11e8-8ece-2bdcf40ea37b.png)

**Comment by scshitole** [comment]
@slodewyk  I would advise to move to the release v12.x instead

**Comment by scshitole** [comment]
We support from 12.X onwards so closing this issue
