### ISSUE TITLE
New version of TCP irule requires both an HTTP profile and Access policy

### ISSUE THREAD

**Issue by chhyde** [f5devcentral/f5-tetration#2]
Hi Sanjay,

The current version of the TCP irule with the HTTP_REQUEST event and the ACCESS::session command require both an HTTP profile and Access policy on the associated virtual servers.  While the username is useful added data, the TCP rule as it stands now cannot be used on virtual servers that do not meet those requirements.

My recommendation is to restore the previous version of the TCP rule and add the current version as an option for use cases that meet the more specific requirement.

Regards,
Chris

**Comment by scshitole** [comment]
@chhyde  thanks I have reverted back to the old irule which does not have HTTP events, will create a new irule with HTTP events or will consolidate in the existing irule.

**Comment by scshitole** [comment]
@chhyde created new irule for http layer 7

https://github.com/f5devcentral/f5-tetration/blob/master/irules/Tetration_HTTP_L7_ipfix.tcl

**Comment by adam-f5** [comment]
Repository Archived
