### ISSUE TITLE
F5 v13 RAM leak with IPFix iRule

### ISSUE THREAD

**Issue by tommy18241** [f5devcentral/f5-tetration#6]
Looks like there is some problem with memory leak durin this iRules work.
We implemented it on our external LTM (there is many VSs tcp\udp\http)

After couple of days our LTM was out of memory because of iRule
We deattached iRules asap, so in the end we not sure what particular iRule was the root cause.
I suppose it can be an HTTP iRule since there is no static variables defined in RULE_INIT block

when RULE_INIT {
  set static::http_rule1_dest ""
  set static::http_rule1_tmplt ""
}

Also the main weak of this script(and other scripts too) is long term sessions.
On our external LTM we can have hundreds of sessions that can live about an 2 hours.
So script will wait for a CLIENT_CLOSED\SERVER_CLOSED events, only when session close it will send actual data.
All this time looks like it will need to store data in RAM untill session closed.

**Comment by scshitole** [comment]
@tommy18241 Is it possible to test with the static variables defined in the HTTP irule, after how much time this problem occurs ?

**Comment by tommy18241** [comment]
The problem was rising for 3-4 days on our External LTM with average 2000 active connections all the time.(it consume about 4GB RAM in the end for iRule process)

We have no ability to enable this script in network again, since there is no trust for it.
We will try to do it in the lab, but there is not the same amount and type of traffic that we have in production.

I think it obvious that script relied on Client\Server session closing event will cause of RAM overload.
Especially on the external LTMs where tons of orphaned sessions could exist for 2 hours(by default), and in RAM they exist the same time until dropped.
Maybe there is a problem with clearing RAM after connection dropped by TCP inactivity timeout, bug for example.

**Comment by scshitole** [comment]
@tommy18241 sorry to bother you do you know which release is your BIG-IP on?

**Comment by scshitole** [comment]
@tommy18241  please let us know which release of BIG-IP

**Comment by adam-f5** [comment]
Repository Archived
